export type AppointListData = {
  age: string
  appointmentDate: string
  appointmentDateStr: string
  appointmentDateTime: string
  appointmentTimeCut: string
  appointmentTimeDisp: string
  appointmentTimeEnd: string
  appointmentTimeStart: string
  appointmentType: string
  approveTime: string
  approver: string
  archivesNo: string
  assignmentDetailId: string
  assignmentDetailStatus: string
  birthday: string
  cmpe: string
  cmpeRemark: string
  conditionRemark: string
  confirmUser: string
  consFee: string
  countBh: string
  countRecipel: string
  createTime: string
  createUser: string
  deliverAddress: string
  deliverMobile: string
  deliverName: string
  discount: string
  doctorId: string
  doctorName: string
  end: string
  hasHighMedicalInsurance: string | boolean
  hospitalId: string
  hospitalName: string
  id: string
  idList: string
  identityCode: string
  identityType: string
  ifInsur: string
  importantGuest: string
  importantGuestComment: string
  importantGuestName: string
  importantName: string
  inspectTime: string
  inspectUser: string
  insurId: string
  insurName: string
  isActivity: string
  isDeleted: string
  isLate: string
  isMoAct: string
  isPush: string
  isSendSms: string
  isUpdateAppointRemark: string
  isUpdateConditionRemark: string
  isValid: string
  levelName: string
  logChannel: string
  marketActivity: string
  memberAge: string
  memberBirthday: string
  memberGender: string
  memberId: string
  memberInsurId: string
  memberInsurName: string
  memberLevel: string
  memberLevelName: string
  memberMobile: string
  memberName: string
  memberPay: boolean
  memberSourceValue: string
  mergeNo: string
  modifyTime: string
  modifyUser: string
  noCancel: string
  note: string
  packageId: string
  packageName: string
  pageNum: number
  pageSize: number
  payMobile: string
  payType: string
  paymentStatus: string
  paymentTime: string
  pendingFlag: string
  pinyinCode: string
  plusType: string
  printTime: string
  registerDate: string
  registerNum: string
  registerType: string
  remark: string
  replyChannel: string
  salutation: string
  smsContent: string
  source: string
  specialistId: string
  specialistName: string
  specialistPlanId: string
  start: string
  state: string
  statisticsId: string
  status: string
  statusText: string
  subType: string
  tkId: string
  tkStatus: string
  type: string
  usePrCard: string
  value: string
  visitClass: string
  visitType: string
  week: string
  workOrderId: string
  wxId: string
}
