export type AppointRegisteredTableData = {
  id: string
  createTime: string
  modifyTime: string
  createUser: string
  modifyUser: string
  isDeleted: string
  pageNum: number
  pageSize: number
  workOrderId: string
  hospitalId: string
  hospitalName: string
  consFee: string
  appointmentTimeStart: string
  doctorId: string
  doctorName: string
  wxId: string
  pinyinCode: string
  memberId: string
  archivesNo: string
  memberName: string
  memberGender: string
  memberMobile: string
  memberBirthday: string
  memberLevel: string
  memberLevelName: string
  visitType: string
  visitClass: string
  appointmentDate: string
  appointmentTimeDisp: string
  assignmentDetailStatus: string
  assignmentDetailId: string
  note: string
  status: string
  appointmentType: string
  salutation: string
  pendingFlag: string
  plusType: string
  source: string
  isActivity: string
  replyChannel: string
  week: string
  specialistPlanId: string
  specialistId: string
  specialistName: string
  packageId: string
  packageName: string
  importantGuest: string
  importantGuestName: string
  importantGuestComment: string
  hasHighMedicalInsurance: string
  appointmentTimeEnd: string
  usePrCard: string
  isPush: string
  isSendSms: string
  type: string
  marketActivity: string
  registerNum: string
  registerType: string
  registerDate: string
  insurId: string
  insurName: string
  memberInsurId: string
  memberInsurName: string
  paymentStatus: string
  statisticsId: string
  payMobile: string
  isUpdateAppointRemark: string
  isUpdateConditionRemark: string
  start: string
  end: string
  cmpe: string
  cmpeRemark: string
  subType: string
  discount: string
  noCancel: string
  conditionRemark: string
  memberPay: string
  logChannel: string
}
